export const GameState = {
  canvas: null,
  ctx: null,
  gameW: 0,
  gameH: 0,
  scaleFactor: 1,
  groundY: 0,
  gameSpeed: 0,
  player: {
    x: 0,
    y: 0,
    size: 0,
    vy: 0,
    jumpForce: 0,
    gravity: 0,
    grounded: false,
    rotation: 0,
    trail: [],
  },
  obstacles: [],
  gridOffset: 0,
  isGameRunning: false,
  score: 0,
  highScore: 0,
  animationId: null,
  gameFrame: 0,
  pixelBlastApp: null,
};
